version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: Create CloudFormation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.16
    steps:
        - checkout # check out the code in the project directory
        
        - run:
            name: Install openssh
            command: |
              apk add openssh

        - add_ssh_keys:
            fingerprints: ["59:32:01:90:81:ad:9a:85:b0:72:8a:96:13:b9:e2:f6"]
              
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible

        - run:
            name: Run playbook and Configure Server
            command: |
              ansible-playbook -i inventory main-remote.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      # - configure_infrastructure
